### ISSUE TITLE
Cannot pass duplicate keys to json5 parser.

### ISSUE THREAD

**Issue by twilson2012** [werk85/grunt-json-minify#7]
Need to expose the ability to ignore duplicate keys with json5 lib.

**Comment by mlegenhausen** [comment]
See pull request ##8.

**Comment by twilson2012** [comment]
What do you need? I provided info on how to use the new parameter and why it was necessary.

Tim

-----Original Message-----

**Comment by mlegenhausen** [comment]
Sure but I can not find any code in the `json5` module that uses this variable? Maybe you can send be a link to the code line where it is used in the external library code.

**Comment by twilson2012** [comment]
Here you go, https://www.npmjs.com/package/json5-utils, let me know if you
need anything else.

- Tim

On Tue, Jun 28, 2016 at 6:52 AM, Malte Legenhausen <notifications@github.com

**Comment by mlegenhausen** [comment]
You can now use your own JSON implementation by using the `transform` option provided by `grunt-json-minify@1.0.1`.

**Comment by ghost** [comment]
Malte,

This is even better, thank you!
- Tim

On Wed, Jun 29, 2016 at 4:08 AM, Malte Legenhausen <notifications@github.com
